name: pytest

on: push

jobs:
  pytest:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: snok/install-poetry@master
      - run: make install

      - name: lint and tests
      - run: make lint
      - run: make pytest

      - name: test coverage
      - uses: paambaati/codeclimate-action@v2.2.4
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage
          debug: true
