name: pytest

on: push

jobs:
  pytest:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@vmaster
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: snok/install-poetry@master
      - run: make install
      - run: make lint
      - run: make pytest
