name: test-coverage

on: push

jobs:
  pytest:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
         python-version: '3.10' 
      - uses: snok/install-poetry@master
      - run: make lint
      - run: make pytest
      - run: make coverage
