name: pytest

on: push

jobs:
  pytest:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: instal poetry and dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
      - run: make lint
      - run: make pytest
